.Dd $Mdocdate$
.Dt ISALPHARUNE 3
.Os
.Sh NAME
.Nm isalpharune, islowerrune, isspacerune, istitlerune, isupperrune, isdigitrune, iscombiningrune
.Nd Unicode rune classification
.Sh SYNOPSIS
.Ft int
.Fn isalpharune "Rune r"
.Ft int
.Fn islowerrune "Rune r"
.Ft int
.Fn isspacerune "Rune r"
.Ft int
.Fn istitlerune "Rune r"
.Ft int
.Fn isupperrune "Rune r"
.Ft int
.Fn isdigitrune "Rune r"
.Sh DESCRIPTION
These functions classify Unicode runes according to their properties defined in the Unicode standard, analogously to
.Xr ctype 3
for ASCII.
.Sh CONFORMING TO
These functions are compatible with those defined in the Plan 9 C library, but are generated automatically from the Unicode $UNICODE Character Database, so classifications may differ.
.Sh SEE ALSO
.Xr ctype 3 ,
.Xr rune 3 ,
The Unicode $UNICODE Standard
